version: '3.8'

services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 2
      KAFKA_LOG_RETENTION_BYTES: 1073741824
    volumes:
      - kafka_data:/var/lib/kafka/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # Porta per le API (Quella che userà PySpark)
      - "9001:9001"  # Porta per la Console Web (Quella che userai tu dal browser)
    environment:
      - MINIO_ROOT_USER=admin          # Questa diventerà la tua ACCESS_KEY
      - MINIO_ROOT_PASSWORD=password123 # Questa diventerà la tua SECRET_KEY
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data  # Salva i file fisicamente in una cartella sul tuo PC

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-gold
    ports:
      - "8123:8123" # Porta HTTP (quella che userà PySpark e Grafana)
      - "9002:9000" # Porta Nativa
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana123
    depends_on:
      - clickhouse
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  kafka_data:
  clickhouse_data:
  minio_data:
  grafana_data: