{
 "title": "Live Retail Data",
 "time": { "from": "2026-04-03T10:52:38.093Z", "to": "2026-04-03T12:13:36.947Z" },
 "templating": {
  "list": [
   {
    "name": "multi_store",
    "label": "select the stores you want to visualize",
    "query": "SELECT DISTINCT store FROM retail_stats.checkout_analytics ORDER BY store"
   },
   {
    "name": "unique_store",
    "label": "Select the Store",
    "query": "SELECT DISTINCT store FROM retail_stats.checkout_analytics ORDER BY store"
   },
   {
    "name": "checkout",
    "label": "Select the Checkouts",
    "query": "SELECT DISTINCT checkout \nFROM retail_stats.checkout_analytics \nWHERE store IN  '$unique_store'\nORDER BY checkout"
   },
   {
    "name": "category",
    "label": "category",
    "query": "SELECT DISTINCT category \nFROM retail_stats.article_analytics \nORDER BY category"
   },
   {
    "name": "model",
    "label": "model",
    "query": "SELECT DISTINCT model\nFROM retail_stats.article_analytics\nWHERE category IN ($category)\nORDER BY model"
   }
  ]
 },
 "panels": [
  {
   "title": "Payment methods in Store $unique_store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    window_start AS time,\r\n    store, \r\n    checkout,\r\n    countIf(payment = 'cash') AS cash_payments,\r\n    countIf(payment = 'card') AS card_payments,\r\n    countIf(payment = 'gift card') AS gift_payments\r\nFROM retail_stats.payment_analytics\r\nWHERE $__timeFilter(window_start)\r\n  AND store = '$unique_store' \r\n  AND checkout IN ($checkout)\r\nGROUP BY store, checkout, window_start\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Detect Problem in Checkout of Store $unique_store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    window_start AS time, \r\n    checkout AS metric,\r\n    ck_return_rate AS return_rate,\r\n    ck_discount AS discount\r\nFROM retail_stats.checkout_analytics\r\nWHERE $__timeFilter(window_start) AND store IN '$unique_store' AND checkout = [${checkout:singlequote}][1]\r\nORDER BY time, metric"
    }
   ]
  },
  {
   "title": "Sales for each Article in selected stores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT sold_articles, window_start, category, model, store\r\nFROM retail_stats.article_analytics\r\nWHERE $__timeFilter(window_start) AND category in ($category) and model in ($model) and store in ($multi_store)"
    }
   ]
  },
  {
   "title": "Profit Comparison between Stores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    window_start AS time, \r\n    sum(ck_net_profit) AS profit,\r\n    store AS metric\r\nFROM retail_stats.checkout_analytics\r\nWHERE $__timeFilter(window_start) and store IN ($multi_store)\r\nGROUP BY window_start, store\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sales in selected Checkouts of store : $unique_store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    window_start AS time, \r\n    checkout AS metric,\r\n    ck_total_sales AS checkout_sales\r\nFROM retail_stats.checkout_analytics\r\nWHERE $__timeFilter(window_start) AND store IN '$unique_store' AND checkout IN ($checkout)\r\nORDER BY time, metric"
    }
   ]
  },
  {
   "title": "Profits and Costs over time for Store : $unique_store ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    window_start AS time, \r\n    ck_net_profit AS net_profit, \r\n    -ck_costs AS cost,\r\n    avg(ck_net_profit) OVER () AS average_profit,\r\n    store\r\nFROM retail_stats.checkout_analytics\r\nWHERE $__timeFilter(window_start) AND store= '$unique_store'               \r\nORDER BY time"
    }
   ]
  }
 ]
}