apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    user: default
    secureJsonData:
      password: "clickhouse123"
    jsonData:
      server: "clickhouse"           
      port: 8123                     
      protocol: "http"               
      defaultDatabase: "retail_stats"
    isDefault: true
    editable: true