CREATE TABLE IF NOT EXISTS inventory (
    id SERIAL PRIMARY KEY,
    store VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    quantity INT NOT NULL,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO inventory(store, category, model, quantity) VALUES
    ('Milan1', 'Jeans', 'Skinny', 100),
    ('Milan1', 'Jeans', 'Slim', 100),
    ('Milan1', 'Jeans', 'Straight', 100),
    ('Milan1', 'Jeans', 'Baggy', 100),
    ('Milan1', 'T-Shirt', 'Basic', 100),
    ('Milan1', 'T-Shirt', 'Graphic Print', 100),
    ('Milan1', 'T-Shirt', 'Polo', 100),
    ('Milan1', 'T-Shirt', 'Crewneck', 100),
    ('Milan1', 'Sweater', 'Zip-Up', 100),
    ('Milan1', 'Sweater', 'Crewneck', 100),
    ('Milan1', 'Sweater', 'Hoodie', 100),
    ('Milan1', 'Jacker', 'Leather', 100),
    ('Milan1', 'Jacket', 'Denim', 100),
    ('Milan1', 'Jacket', 'Bomber', 100),
    ('Milan1', 'Jacket', 'Puffer', 100),
    ('Milan1', 'Shoes', 'Canvas', 100),
    ('Milan1', 'Shoes', 'Running', 100),
    ('Milan1', 'Shoes', 'Chunky', 100),
    ('Milan1', 'Shoes', 'High-Top', 100),
    ('Milan1', 'Socks', 'Ankle (3-pack)', 100),
    ('Milan1', 'Socks', 'Crew', 100),
    ('Milan1', 'Socks', 'Sport', 100),

    ('Milan2', 'Jeans', 'Skinny', 100),
    ('Milan2', 'Jeans', 'Slim', 100),
    ('Milan2', 'Jeans', 'Straight', 100),
    ('Milan2', 'Jeans', 'Baggy', 100),
    ('Milan2', 'T-Shirt', 'Basic', 100),
    ('Milan2', 'T-Shirt', 'Graphic Print', 100),
    ('Milan2', 'T-Shirt', 'Polo', 100),
    ('Milan2', 'T-Shirt', 'Crewneck', 100),
    ('Milan2', 'Sweater', 'Zip-Up', 100),
    ('Milan2', 'Sweater', 'Crewneck', 100),
    ('Milan2', 'Sweater', 'Hoodie', 100),
    ('Milan2', 'Jacker', 'Leather', 100),
    ('Milan2', 'Jacket', 'Denim', 100),
    ('Milan2', 'Jacket', 'Bomber', 100),
    ('Milan2', 'Jacket', 'Puffer', 100),
    ('Milan2', 'Shoes', 'Canvas', 100),
    ('Milan2', 'Shoes', 'Running', 100),
    ('Milan2', 'Shoes', 'Chunky', 100),
    ('Milan2', 'Shoes', 'High-Top', 100),
    ('Milan2', 'Socks', 'Ankle (3-pack)', 100),
    ('Milan2', 'Socks', 'Crew', 100),
    ('Milan2', 'Socks', 'Sport', 100),

    ('Milan3', 'Jeans', 'Skinny', 100),
    ('Milan3', 'Jeans', 'Slim', 100),
    ('Milan3', 'Jeans', 'Straight', 100),
    ('Milan3', 'Jeans', 'Baggy', 100),
    ('Milan3', 'T-Shirt', 'Basic', 100),
    ('Milan3', 'T-Shirt', 'Graphic Print', 100),
    ('Milan3', 'T-Shirt', 'Polo', 100),
    ('Milan3', 'T-Shirt', 'Crewneck', 100),
    ('Milan3', 'Sweater', 'Zip-Up', 100),
    ('Milan3', 'Sweater', 'Crewneck', 100),
    ('Milan3', 'Sweater', 'Hoodie', 100),
    ('Milan3', 'Jacker', 'Leather', 100),
    ('Milan3', 'Jacket', 'Denim', 100),
    ('Milan3', 'Jacket', 'Bomber', 100),
    ('Milan3', 'Jacket', 'Puffer', 100),
    ('Milan3', 'Shoes', 'Canvas', 100),
    ('Milan3', 'Shoes', 'Running', 100),
    ('Milan3', 'Shoes', 'Chunky', 100),
    ('Milan3', 'Shoes', 'High-Top', 100),
    ('Milan3', 'Socks', 'Ankle (3-pack)', 100),
    ('Milan3', 'Socks', 'Crew', 100),
    ('Milan3', 'Socks', 'Sport', 100),

    ('Milan4', 'Jeans', 'Skinny', 100),
    ('Milan4', 'Jeans', 'Slim', 100),
    ('Milan4', 'Jeans', 'Straight', 100),
    ('Milan4', 'Jeans', 'Baggy', 100),
    ('Milan4', 'T-Shirt', 'Basic', 100),
    ('Milan4', 'T-Shirt', 'Graphic Print', 100),
    ('Milan4', 'T-Shirt', 'Polo', 100),
    ('Milan4', 'T-Shirt', 'Crewneck', 100),
    ('Milan4', 'Sweater', 'Zip-Up', 100),
    ('Milan4', 'Sweater', 'Crewneck', 100),
    ('Milan4', 'Sweater', 'Hoodie', 100),
    ('Milan4', 'Jacker', 'Leather', 100),
    ('Milan4', 'Jacket', 'Denim', 100),
    ('Milan4', 'Jacket', 'Bomber', 100),
    ('Milan4', 'Jacket', 'Puffer', 100),
    ('Milan4', 'Shoes', 'Canvas', 100),
    ('Milan4', 'Shoes', 'Running', 100),
    ('Milan4', 'Shoes', 'Chunky', 100),
    ('Milan4', 'Shoes', 'High-Top', 100),
    ('Milan4', 'Socks', 'Ankle (3-pack)', 100),
    ('Milan4', 'Socks', 'Crew', 100),
    ('Milan4', 'Socks', 'Sport', 100),

    ('Rome1', 'Jeans', 'Skinny', 100),
    ('Rome1', 'Jeans', 'Slim', 100),
    ('Rome1', 'Jeans', 'Straight', 100),
    ('Rome1', 'Jeans', 'Baggy', 100),
    ('Rome1', 'T-Shirt', 'Basic', 100),
    ('Rome1', 'T-Shirt', 'Graphic Print', 100),
    ('Rome1', 'T-Shirt', 'Polo', 100),
    ('Rome1', 'T-Shirt', 'Crewneck', 100),
    ('Rome1', 'Sweater', 'Zip-Up', 100),
    ('Rome1', 'Sweater', 'Crewneck', 100),
    ('Rome1', 'Sweater', 'Hoodie', 100),
    ('Rome1', 'Jacker', 'Leather', 100),
    ('Rome1', 'Jacket', 'Denim', 100),
    ('Rome1', 'Jacket', 'Bomber', 100),
    ('Rome1', 'Jacket', 'Puffer', 100),
    ('Rome1', 'Shoes', 'Canvas', 100),
    ('Rome1', 'Shoes', 'Running', 100),
    ('Rome1', 'Shoes', 'Chunky', 100),
    ('Rome1', 'Shoes', 'High-Top', 100),
    ('Rome1', 'Socks', 'Ankle (3-pack)', 100),
    ('Rome1', 'Socks', 'Crew', 100),
    ('Rome1', 'Socks', 'Sport', 100),

    ('Rome2', 'Jeans', 'Skinny', 100),
    ('Rome2', 'Jeans', 'Slim', 100),
    ('Rome2', 'Jeans', 'Straight', 100),
    ('Rome2', 'Jeans', 'Baggy', 100),
    ('Rome2', 'T-Shirt', 'Basic', 100),
    ('Rome2', 'T-Shirt', 'Graphic Print', 100),
    ('Rome2', 'T-Shirt', 'Polo', 100),
    ('Rome2', 'T-Shirt', 'Crewneck', 100),
    ('Rome2', 'Sweater', 'Zip-Up', 100),
    ('Rome2', 'Sweater', 'Crewneck', 100),
    ('Rome2', 'Sweater', 'Hoodie', 100),
    ('Rome2', 'Jacker', 'Leather', 100),
    ('Rome2', 'Jacket', 'Denim', 100),
    ('Rome2', 'Jacket', 'Bomber', 100),
    ('Rome2', 'Jacket', 'Puffer', 100),
    ('Rome2', 'Shoes', 'Canvas', 100),
    ('Rome2', 'Shoes', 'Running', 100),
    ('Rome2', 'Shoes', 'Chunky', 100),
    ('Rome2', 'Shoes', 'High-Top', 100),
    ('Rome2', 'Socks', 'Ankle (3-pack)', 100),
    ('Rome2', 'Socks', 'Crew', 100),
    ('Rome2', 'Socks', 'Sport', 100),

    ('Rome3', 'Jeans', 'Skinny', 100),
    ('Rome3', 'Jeans', 'Slim', 100),
    ('Rome3', 'Jeans', 'Straight', 100),
    ('Rome3', 'Jeans', 'Baggy', 100),
    ('Rome3', 'T-Shirt', 'Basic', 100),
    ('Rome3', 'T-Shirt', 'Graphic Print', 100),
    ('Rome3', 'T-Shirt', 'Polo', 100),
    ('Rome3', 'T-Shirt', 'Crewneck', 100),
    ('Rome3', 'Sweater', 'Zip-Up', 100),
    ('Rome3', 'Sweater', 'Crewneck', 100),
    ('Rome3', 'Sweater', 'Hoodie', 100),
    ('Rome3', 'Jacker', 'Leather', 100),
    ('Rome3', 'Jacket', 'Denim', 100),
    ('Rome3', 'Jacket', 'Bomber', 100),
    ('Rome3', 'Jacket', 'Puffer', 100),
    ('Rome3', 'Shoes', 'Canvas', 100),
    ('Rome3', 'Shoes', 'Running', 100),
    ('Rome3', 'Shoes', 'Chunky', 100),
    ('Rome3', 'Shoes', 'High-Top', 100),
    ('Rome3', 'Socks', 'Ankle (3-pack)', 100),
    ('Rome3', 'Socks', 'Crew', 100),
    ('Rome3', 'Socks', 'Sport', 100),

    ('Naples1', 'Jeans', 'Skinny', 100),
    ('Naples1', 'Jeans', 'Slim', 100),
    ('Naples1', 'Jeans', 'Straight', 100),
    ('Naples1', 'Jeans', 'Baggy', 100),
    ('Naples1', 'T-Shirt', 'Basic', 100),
    ('Naples1', 'T-Shirt', 'Graphic Print', 100),
    ('Naples1', 'T-Shirt', 'Polo', 100),
    ('Naples1', 'T-Shirt', 'Crewneck', 100),
    ('Naples1', 'Sweater', 'Zip-Up', 100),
    ('Naples1', 'Sweater', 'Crewneck', 100),
    ('Naples1', 'Sweater', 'Hoodie', 100),
    ('Naples1', 'Jacker', 'Leather', 100),
    ('Naples1', 'Jacket', 'Denim', 100),
    ('Naples1', 'Jacket', 'Bomber', 100),
    ('Naples1', 'Jacket', 'Puffer', 100),
    ('Naples1', 'Shoes', 'Canvas', 100),
    ('Naples1', 'Shoes', 'Running', 100),
    ('Naples1', 'Shoes', 'Chunky', 100),
    ('Naples1', 'Shoes', 'High-Top', 100),
    ('Naples1', 'Socks', 'Ankle (3-pack)', 100),
    ('Naples1', 'Socks', 'Crew', 100),
    ('Naples1', 'Socks', 'Sport', 100),

    ('Turin1', 'Jeans', 'Skinny', 100),
    ('Turin1', 'Jeans', 'Slim', 100),
    ('Turin1', 'Jeans', 'Straight', 100),
    ('Turin1', 'Jeans', 'Baggy', 100),
    ('Turin1', 'T-Shirt', 'Basic', 100),
    ('Turin1', 'T-Shirt', 'Graphic Print', 100),
    ('Turin1', 'T-Shirt', 'Polo', 100),
    ('Turin1', 'T-Shirt', 'Crewneck', 100),
    ('Turin1', 'Sweater', 'Zip-Up', 100),
    ('Turin1', 'Sweater', 'Crewneck', 100),
    ('Turin1', 'Sweater', 'Hoodie', 100),
    ('Turin1', 'Jacker', 'Leather', 100),
    ('Turin1', 'Jacket', 'Denim', 100),
    ('Turin1', 'Jacket', 'Bomber', 100),
    ('Turin1', 'Jacket', 'Puffer', 100),
    ('Turin1', 'Shoes', 'Canvas', 100),
    ('Turin1', 'Shoes', 'Running', 100),
    ('Turin1', 'Shoes', 'Chunky', 100),
    ('Turin1', 'Shoes', 'High-Top', 100),
    ('Turin1', 'Socks', 'Ankle (3-pack)', 100),
    ('Turin1', 'Socks', 'Crew', 100),
    ('Turin1', 'Socks', 'Sport', 100),

    ('Venice1', 'Jeans', 'Skinny', 100),
    ('Venice1', 'Jeans', 'Slim', 100),
    ('Venice1', 'Jeans', 'Straight', 100),
    ('Venice1', 'Jeans', 'Baggy', 100),
    ('Venice1', 'T-Shirt', 'Basic', 100),
    ('Venice1', 'T-Shirt', 'Graphic Print', 100),
    ('Venice1', 'T-Shirt', 'Polo', 100),
    ('Venice1', 'T-Shirt', 'Crewneck', 100),
    ('Venice1', 'Sweater', 'Zip-Up', 100),
    ('Venice1', 'Sweater', 'Crewneck', 100),
    ('Venice1', 'Sweater', 'Hoodie', 100),
    ('Venice1', 'Jacker', 'Leather', 100),
    ('Venice1', 'Jacket', 'Denim', 100),
    ('Venice1', 'Jacket', 'Bomber', 100),
    ('Venice1', 'Jacket', 'Puffer', 100),
    ('Venice1', 'Shoes', 'Canvas', 100),
    ('Venice1', 'Shoes', 'Running', 100),
    ('Venice1', 'Shoes', 'Chunky', 100),
    ('Venice1', 'Shoes', 'High-Top', 100),
    ('Venice1', 'Socks', 'Ankle (3-pack)', 100),
    ('Venice1', 'Socks', 'Crew', 100),
    ('Venice1', 'Socks', 'Sport', 100);
